10 SCREEN 9
FOR x = 1 TO 3000: NEXT x
20 CIRCLE (285, 167), 200
a = 1
PSET (255, 117)
DRAW "r50d50l50r50d50l50"
FOR x = 1 TO 2000: NEXT x
CLS
CIRCLE (285, 167), 200
PSET (255, 117)
DRAW "r50d50l50d50r50"
FOR x = 1 TO 2000: NEXT x
CLS
CIRCLE (285, 167), 200
PSET (235, 167)
DRAW "e50d100"
FOR x = 1 TO 2500: NEXT x
CLS

FOR x = 1 TO 4000: NEXT x
REM                                         musica e simbolo
PLAY "mbp10l5n32l5n34l5l5n36l5n37l5n36l3n39"
COLOR 8, 0
LOCATE 12, 24: PRINT "A  CLAUDIOSOFT  PRODUCTION"
x = 1
COLOR 14
FOR x = 1 TO 45
x = x + 8
CIRCLE (290, 230), x, , , , 9 / 40
NEXT x
FOR x = 1 TO 3000: NEXT x

COLOR 15, 0
LOCATE 12, 24: PRINT "A  CLAUDIOSOFT  PRODUCTION"
FOR x = 1 TO 5500: NEXT x
COLOR 8, 0
LOCATE 12, 24: PRINT "A  CLAUDIOSOFT  PRODUCTION"
FOR x = 1 TO 3000: NEXT x
CLS
FOR x = 1 TO 4000: NEXT x
REM                                    resto....
45 CLS
FOR x = 1 TO 2000: NEXT x
COLOR 3
 d = 1
FOR x = 1 TO 200
d = d + 1
CIRCLE (310, 190), d, , , , 10 / 50
NEXT x
COLOR 12
LOCATE 14, 22
PRINT " S U B M A R I N E     M I S S I O N "
FOR x = 1 TO 9000: NEXT x
CLS
FOR x = 1 TO 2000: NEXT x
COLOR 14
LOCATE 12, 24
PRINT " Programmatori : Claudio Tortorelli"
FOR x = 1 TO 4000: NEXT x
CLS
FOR x = 1 TO 1500: NEXT x
LOCATE 12, 24
PRINT " Ideatori : Claudio Tortorelli"
FOR x = 1 TO 3500: NEXT x
CLS
FOR x = 1 TO 1500: NEXT x
LOCATE 12, 24
PRINT " Realizzazione musicale : Claudio Tortorelli"
FOR x = 1 TO 3500: NEXT x
CLS
FOR x = 1 TO 1500: NEXT x
LOCATE 12, 24
PRINT " Realizzazione grafica : Claudio Tortorelli"
FOR x = 1 TO 3500: NEXT x
CLS
FOR x = 1 TO 1500: NEXT x
LOCATE 12, 24
PRINT " Realizzazione animazioni : Claudio Tortorelli"
FOR x = 1 TO 3500: NEXT x
CLS
FOR x = 1 TO 1500: NEXT x
LOCATE 12, 24
PRINT " CLAUDIOSOFT -----  COPYRIGHT 1992ø "
FOR x = 1 TO 4000: NEXT x

